/// Data models for the Nymbot client surface.
///
/// Field names mirror the `functions/api/bot.js` worker response shapes and the
/// client contract in `docs/specs/04-features.md` §11.2-11.5.
library;

/// The Pro frontier models selectable with `?model <name>`.
///
/// Exact list + ids verified against `functions/api/bot.js` `BOT_PRO_MODELS`
/// (and README line 170 / spec §11.3). [key] is the value sent as `proModel`;
/// [label] is the README's display name; [baseCredits] is the per-call base
/// Pro-credit cost (1, except Fable = 2).
class ProModel {
  const ProModel({
    required this.key,
    required this.label,
    required this.modelId,
    required this.baseCredits,
  });

  /// Value passed to the worker as `proModel`, e.g. `claude-opus`.
  final String key;

  /// README display label, e.g. `Claude Opus 4.8`.
  final String label;

  /// Internal provider/model id, e.g. `anthropic/claude-opus-4.8`.
  final String modelId;

  /// Base Pro credits charged per model call (before length scaling).
  final int baseCredits;
}

/// The 7 Pro models, in README order (line 170):
/// Claude Fable 5, Claude Opus 4.8, Claude Sonnet 4.6, Claude Haiku 4.5,
/// GPT-5.1, GPT-5 mini, GPT-5.1 Codex.
const List<ProModel> kProModels = [
  ProModel(
    key: 'claude-fable',
    label: 'Claude Fable 5',
    modelId: 'anthropic/claude-fable-5',
    baseCredits: 2,
  ),
  ProModel(
    key: 'claude-opus',
    label: 'Claude Opus 4.8',
    modelId: 'anthropic/claude-opus-4.8',
    baseCredits: 1,
  ),
  ProModel(
    key: 'claude-sonnet',
    label: 'Claude Sonnet 4.6',
    modelId: 'anthropic/claude-sonnet-4.6',
    baseCredits: 1,
  ),
  ProModel(
    key: 'claude-haiku',
    label: 'Claude Haiku 4.5',
    modelId: 'anthropic/claude-haiku-4.5',
    baseCredits: 1,
  ),
  ProModel(
    key: 'gpt-5',
    label: 'GPT-5.1',
    modelId: 'openai/gpt-5.1',
    baseCredits: 1,
  ),
  ProModel(
    key: 'gpt-5-mini',
    label: 'GPT-5 mini',
    modelId: 'openai/gpt-5-mini',
    baseCredits: 1,
  ),
  ProModel(
    key: 'codex',
    label: 'GPT-5.1 Codex',
    modelId: 'openai/gpt-5.1-codex',
    baseCredits: 1,
  ),
];

/// Looks up a Pro model by its `?model` argument. Accepts the canonical [key]
/// as well as a loose match on the label (case-insensitive). Returns null for
/// unknown names or the literal `off`.
ProModel? lookupProModel(String name) {
  final n = name.trim().toLowerCase();
  if (n.isEmpty || n == 'off') return null;
  for (final m in kProModels) {
    if (m.key == n) return m;
    if (m.label.toLowerCase() == n) return m;
  }
  // Loose contains match (e.g. "opus" -> Claude Opus 4.8).
  for (final m in kProModels) {
    if (m.label.toLowerCase().contains(n) || m.key.contains(n)) return m;
  }
  return null;
}

/// Result of splitting a bot reply into its visible text and optional
/// `<think>…</think>` reasoning (spec §11.5; worker `sanitizeBotResponse`).
class BotReply {
  const BotReply({
    required this.text,
    this.reasoning,
    this.taskType,
    this.modelCalls,
    this.outputTokens,
    this.cost,
    this.balance,
    this.pro = false,
    this.proModel,
    this.git = false,
    this.lowBalance = false,
  });

  /// The reply body with any reasoning block stripped out.
  final String text;

  /// The extracted reasoning (contents of `<think>…</think>`), or null.
  final String? reasoning;

  /// Auto-router classification, e.g. `coding`/`reasoning`/`creative`/
  /// `translation`/`general`/`pro` (worker `taskType`).
  final String? taskType;

  /// Number of model calls made (git agent loop can use up to 6).
  final int? modelCalls;

  /// Output tokens generated by the reply.
  final int? outputTokens;

  /// Credits charged for this reply.
  final int? cost;

  /// Remaining balance after the reply (tier depends on [pro]).
  final int? balance;

  /// True when answered by a pinned Pro model.
  final bool pro;

  /// The Pro model key used, when [pro].
  final String? proModel;

  /// True when the reply ran in git/repo mode.
  final bool git;

  /// Worker hint that the balance is now low.
  final bool lowBalance;

  bool get hasReasoning => reasoning != null && reasoning!.trim().isNotEmpty;

  /// Cap mirrors the worker's `BOT_THINKING_MAX_CHARS` (4000) — the client
  /// should not render more reasoning than the worker would send.
  static const int kReasoningMaxChars = 4000;
}

/// Standard + Pro credit balances (`action: balance`).
/// Field names verified against worker response (lines 1254-1260) and spec §11.5
/// `BotBalance`.
class BotBalance {
  const BotBalance({
    required this.balance,
    required this.totalPurchased,
    required this.totalUsed,
    required this.proBalance,
    required this.proTotalPurchased,
    required this.proTotalUsed,
  });

  final int balance; // standard credits available
  final int totalPurchased;
  final int totalUsed;
  final int proBalance; // Pro credits available
  final int proTotalPurchased;
  final int proTotalUsed;

  factory BotBalance.fromJson(Map<String, dynamic> j) => BotBalance(
        balance: _int(j['balance']),
        totalPurchased: _int(j['totalPurchased']),
        totalUsed: _int(j['totalUsed']),
        proBalance: _int(j['proBalance']),
        proTotalPurchased: _int(j['proTotalPurchased']),
        proTotalUsed: _int(j['proTotalUsed']),
      );

  static const empty = BotBalance(
    balance: 0,
    totalPurchased: 0,
    totalUsed: 0,
    proBalance: 0,
    proTotalPurchased: 0,
    proTotalUsed: 0,
  );
}

/// Credit tier for buys/balances.
enum CreditTier { standard, pro }

extension CreditTierWire on CreditTier {
  String get wire => this == CreditTier.pro ? 'pro' : 'standard';

  /// Sats per credit (README line 170): Standard = 10, Pro = 100.
  int get satsPerCredit => this == CreditTier.pro ? 100 : 10;
}

/// A Lightning invoice returned by `action: create-invoice`.
/// Fields verified against worker (lines 1347-1353) + spec §11.2.
class BotInvoice {
  const BotInvoice({
    required this.pr,
    required this.invoiceId,
    this.verify,
    this.serverVerify = false,
    this.needsReceipt = false,
    this.tier = CreditTier.standard,
    this.amountSats = 0,
  });

  /// BOLT11 invoice string (render as QR + copyable text).
  final String pr;

  /// SHA256 of [pr]; used to poll `check-invoice` / `claim-credits`.
  final String invoiceId;

  /// LUD-21 verify URL, when the wallet supports it.
  final String? verify;

  /// True when the server can verify the payment itself (NWC).
  final bool serverVerify;

  /// True when the client must supply a NIP-57 receipt to claim.
  final bool needsReceipt;

  final CreditTier tier;
  final int amountSats;

  factory BotInvoice.fromJson(
    Map<String, dynamic> j, {
    CreditTier tier = CreditTier.standard,
    int amountSats = 0,
  }) =>
      BotInvoice(
        pr: (j['pr'] ?? '').toString(),
        invoiceId: (j['invoiceId'] ?? '').toString(),
        verify: j['verify']?.toString(),
        serverVerify: j['serverVerify'] == true,
        needsReceipt: j['needsReceipt'] == true,
        tier: tier,
        amountSats: amountSats,
      );
}

/// Git provider for the `?git` connect flow (spec §11.4).
enum GitProvider { github, gitlab, gitea }

extension GitProviderWire on GitProvider {
  String get wire => switch (this) {
        GitProvider.github => 'github',
        GitProvider.gitlab => 'gitlab',
        GitProvider.gitea => 'gitea',
      };

  String get label => switch (this) {
        GitProvider.github => 'GitHub',
        GitProvider.gitlab => 'GitLab',
        GitProvider.gitea => 'Gitea / Forgejo',
      };

  /// Default API host for the provider (Gitea defaults to Codeberg).
  String get defaultHost => switch (this) {
        GitProvider.github => 'github.com',
        GitProvider.gitlab => 'gitlab.com',
        GitProvider.gitea => 'codeberg.org',
      };
}

/// On-device git connection config. The [token] (PAT) is stored client-side
/// only and wiped by Panic Mode — it is sent per request and never persisted
/// server-side (spec §11.4). Mirrors spec §11.5 `GitConfig`.
class GitConfig {
  const GitConfig({
    required this.provider,
    required this.host,
    required this.token,
    required this.repo,
    this.branch,
    this.allowWrites = false,
  });

  final GitProvider provider;
  final String host;
  final String token; // PAT — on-device only.
  final String repo; // owner/repo (or group/subgroup/repo on GitLab)
  final String? branch;
  final bool allowWrites; // toggled by `?git writes on`.

  Map<String, dynamic> toWire() => {
        'provider': provider.wire,
        'host': host,
        'token': token,
        'repo': repo,
        if (branch != null && branch!.isNotEmpty) 'branch': branch,
        'allowWrites': allowWrites,
      };

  GitConfig copyWith({
    GitProvider? provider,
    String? host,
    String? token,
    String? repo,
    String? branch,
    bool? allowWrites,
  }) =>
      GitConfig(
        provider: provider ?? this.provider,
        host: host ?? this.host,
        token: token ?? this.token,
        repo: repo ?? this.repo,
        branch: branch ?? this.branch,
        allowWrites: allowWrites ?? this.allowWrites,
      );
}

int _int(Object? v) {
  if (v is int) return v;
  if (v is num) return v.toInt();
  if (v is String) return int.tryParse(v) ?? 0;
  return 0;
}

/// Splits a raw model reply into visible text + `<think>…</think>` reasoning.
///
/// Mirrors the worker's `<think>` convention (`sanitizeBotResponse`, bot.js
/// lines 2397-2432): one or more `<think>…</think>` blocks are removed from the
/// body and concatenated (newline-separated) into [BotReply.reasoning]. The
/// match is case-insensitive and dot-all (spans newlines). Pure — no network.
BotReply splitReasoning(
  String raw, {
  String? taskType,
  int? modelCalls,
  int? outputTokens,
  int? cost,
  int? balance,
  bool pro = false,
  String? proModel,
  bool git = false,
  bool lowBalance = false,
}) {
  final buf = StringBuffer();
  final body = raw.replaceAllMapped(
    RegExp(r'<think>([\s\S]*?)<\/think>', caseSensitive: false),
    (m) {
      final inner = (m.group(1) ?? '').trim();
      if (inner.isNotEmpty) {
        if (buf.isNotEmpty) buf.write('\n\n');
        buf.write(inner);
      }
      return '';
    },
  );

  var reasoning = buf.isEmpty ? null : buf.toString();
  if (reasoning != null && reasoning.length > BotReply.kReasoningMaxChars) {
    reasoning =
        '${reasoning.substring(0, BotReply.kReasoningMaxChars)}\n… [reasoning truncated]';
  }

  return BotReply(
    text: body.trim(),
    reasoning: reasoning,
    taskType: taskType,
    modelCalls: modelCalls,
    outputTokens: outputTokens,
    cost: cost,
    balance: balance,
    pro: pro,
    proModel: proModel,
    git: git,
    lowBalance: lowBalance,
  );
}
